services:

  app: # Имя сервиса
    build:
      # Контекст для сборки образа,
      # в данном случае, текущая директория
      context: ./
      # Имя Docker-файла из которого будет собран образ
      dockerfile: Dockerfile
    ports: # Проброс портов
      - "8080:8080"